/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Student;
import util.JDBCUtils;
import util.UiUtil;

/**
 *
 * @author Glimmer
 */
public class InputGradeUI extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel();

    /**
     * Creates new form InputGradeUI
     */
    public InputGradeUI() {
        initComponents();
        init();
    }

    private void init() {
        this.setTitle("录入分数");
        UiUtil.setFrameCenter(this);
        UiUtil.setFrameImage(this);

        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputid = new javax.swing.JTextField();
        Istuid_fk = new javax.swing.JTextField();
        Iname = new javax.swing.JTextField();
        Ichinese = new javax.swing.JTextField();
        Imath = new javax.swing.JTextField();
        Isex = new javax.swing.JTextField();
        Ienglish = new javax.swing.JTextField();
        Iemail = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ichiense = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("黑体", 0, 14)); // NOI18N
        jLabel1.setText("请输入需要录入分数的学生的学号：");

        inputid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputidActionPerformed(evt);
            }
        });

        Istuid_fk.setEditable(false);
        Istuid_fk.setBackground(new java.awt.Color(204, 204, 204));
        Istuid_fk.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        Iname.setEditable(false);
        Iname.setBackground(new java.awt.Color(204, 204, 204));
        Iname.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));
        Iname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InameActionPerformed(evt);
            }
        });

        Isex.setEditable(false);
        Isex.setBackground(new java.awt.Color(204, 204, 204));
        Isex.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        Iemail.setEditable(false);
        Iemail.setBackground(new java.awt.Color(204, 204, 204));
        Iemail.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), null));

        jButton2.setText("录入分数");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("查询");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("学号：");

        jLabel3.setText("姓名：");

        Ichiense.setText("语文分数：");

        jLabel5.setText("数学分数：");

        jLabel6.setText("性别：");

        jLabel7.setText("英语分数：");

        jLabel8.setText("邮箱：");

        jButton1.setFont(new java.awt.Font("华文彩云", 0, 14)); // NOI18N
        jButton1.setText("返回菜单");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Iname)
                                    .addComponent(Istuid_fk)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(28, 28, 28)
                                .addComponent(Iemail, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(Ichiense))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(Ichinese, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Imath, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ienglish))))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(Isex, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inputid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButton1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Istuid_fk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Iname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Isex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ichiense)
                            .addComponent(Ichinese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Imath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addComponent(Ienglish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel7)))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Iemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//返回菜单
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuUI me = new MenuUI();
        me.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputidActionPerformed

    private void InameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InameActionPerformed
    //先查询是否有该学生
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Student stu = new Student();
        float gradenull = 10000;//表示空的分数

        try {
            // TODO add your handling code here:
        //获取用户输入的学号并判断是否有输入
            if(inputid.getText().trim().length()!=0){
            int stu_id = Integer.parseInt(inputid.getText().trim());
            stu = JDBCUtils.findById(stu_id);
            }
            else{
              JOptionPane.showMessageDialog(null, "请输入要查询的学号", "警告", JOptionPane.WARNING_MESSAGE);
              return;
            }
           

        } catch (Exception ex) {
            Logger.getLogger(FindStudentUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (stu != null) {
            //将查到的值赋值给文本框
            Istuid_fk.setText(Integer.toString(stu.getStuid()));
            Iname.setText(stu.getName());
            Isex.setText(stu.getSex());
            Iemail.setText(stu.getEmail());
            if ((stu.getChinese() == gradenull && stu.getMath() == gradenull) && stu.getEnglish() == gradenull) {
                Ichinese.setText("");
                Imath.setText("");
                Ienglish.setText("");
            } else {

                Ichinese.setText(Float.toString(stu.getChinese()));
                Imath.setText(Float.toString(stu.getMath()));
                Ienglish.setText(Float.toString(stu.getEnglish()));
            }

        } else {
            JOptionPane.showMessageDialog(null, "该学生不存在！", "错误", JOptionPane.WARNING_MESSAGE);
            Istuid_fk.setText("");
            return;
        }
    }//GEN-LAST:event_jButton3ActionPerformed
//录入分数
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Student stu = new Student();

        //判断是否填入值
        boolean f1 = (Ichinese.getText().trim().length() != 0) && (Imath.getText().trim().length() != 0) && (Ienglish.getText().trim().length() != 0);
        if (f1) {
            System.out.println("1111");
            int stuid_fk = Integer.parseInt(Istuid_fk.getText().trim());
            float chinese = Float.parseFloat(Ichinese.getText().trim());
            float math = Float.parseFloat(Imath.getText().trim());
            float english = Float.parseFloat(Ienglish.getText().trim());
//判断分数是否合理
            boolean f2 = (chinese >= 0 && chinese <= 100) || ((math >= 0 && math <= 100)) || ((english >= 0 && english <= 100));
            if (!f2) {
                JOptionPane.showMessageDialog(null, "注：分数需在0-100之间！", "错误", JOptionPane.WARNING_MESSAGE);
                clearInfo();
                return;
            } else {
                System.out.println("22222");
                stu.setStuid_fk(stuid_fk);
                stu.setChinese(chinese);
                stu.setMath(math);
                stu.setEnglish(english);
                if (JDBCUtils.doCreate2(stu)) {
                    JOptionPane.showMessageDialog(null, "录入成功！");
                    clearInfo();
                } else {
                    JOptionPane.showMessageDialog(null, "录入失败！");
                    clearInfo();
                    return;
                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "请填写完整信息！", "错误", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton2ActionPerformed
    private void clearInfo() {
        inputid.setText("");
        Istuid_fk.setText("");
        Iname.setText("");
        Isex.setText("");
        Iemail.setText("");
        Ichinese.setText("");
        Imath.setText("");
        Ienglish.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputGradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputGradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputGradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputGradeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputGradeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ichiense;
    private javax.swing.JTextField Ichinese;
    private javax.swing.JTextField Iemail;
    private javax.swing.JTextField Ienglish;
    private javax.swing.JTextField Imath;
    private javax.swing.JTextField Iname;
    private javax.swing.JTextField Isex;
    private javax.swing.JTextField Istuid_fk;
    private javax.swing.JTextField inputid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
