/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Student;
import util.JDBCUtils;
import util.UiUtil;

/**
 *
 * @author Glimmer
 */
public class MenuUI extends javax.swing.JFrame {

    private JPanel pelBg;

    /**
     * Creates new form MenuUI
     */
    public MenuUI() {
        initComponents();
        init();
    }

    private void init() {
        this.setTitle("主界面");
        UiUtil.setFrameCenter(this);
        UiUtil.setFrameImage(this);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setFont(new java.awt.Font("华文彩云", 0, 18)); // NOI18N
        jButton1.setText("1、学生管理");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("华文彩云", 0, 18)); // NOI18N
        jButton2.setText("2、录入分数");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("华文彩云", 0, 18)); // NOI18N
        jButton5.setText("3、查询最高分学生");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("华文彩云", 0, 18)); // NOI18N
        jButton6.setText("5、返回登陆界面");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("华文彩云", 0, 18)); // NOI18N
        jButton7.setText("4、查询最低分学生");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addGap(96, 96, 96))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(21, 21, 21)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton6))
        );

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setFont(new java.awt.Font("华文彩云", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("菜单");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(238, 238, 238))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //进入学生管理系统界面
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        StudentAdminUI sai = new StudentAdminUI();
        sai.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
//返回主界面
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LoginUI log = new LoginUI();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed
//录入分数
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        InputGradeUI inp = new InputGradeUI();
        inp.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton2ActionPerformed
//查询最高分
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Student stu = new Student();
        int maxgrade = 0;
        try {
            String sql = "select student.stuid,student.name,student.sex,student.email,(grade.chinese+grade.math+grade.english)总分 from student left join grade on student.stuid=grade.stuid_fk where (grade.chinese+grade.math+grade.english in (select max(grade.chinese+grade.math+grade.english)from grade));";
            ResultSet rs = JDBCUtils.executeQuery(sql);
            while (rs.next()) {
                stu.setStuid(rs.getInt("stuid"));
                stu.setName(rs.getString("name"));
                stu.setSex(rs.getString("sex"));
                stu.setEmail(rs.getString("email"));
                maxgrade = rs.getInt("总分");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            JDBCUtils.close(JDBCUtils.getRs(), JDBCUtils.getPs(),
                    JDBCUtils.getCt());
        }
        JOptionPane.showMessageDialog(null, "最高分的学生学号：" + stu.getStuid() + "，姓名："
                + stu.getName() + "，性别：" + stu.getSex() + "，总分：" + maxgrade);
    }//GEN-LAST:event_jButton5ActionPerformed
//查询最低分
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Student stu = new Student();
        int mingrade = 0;
        try {
            String sql = "select student.stuid,student.name,student.sex,student.email,(grade.chinese+grade.math+grade.english)总分 from student left join grade on student.stuid=grade.stuid_fk where (grade.chinese+grade.math+grade.english in (select min(grade.chinese+grade.math+grade.english)from grade));";
            ResultSet rs = JDBCUtils.executeQuery(sql);
            while (rs.next()) {

                stu.setStuid(rs.getInt("stuid"));
                stu.setName(rs.getString("name"));
                stu.setSex(rs.getString("sex"));
                stu.setEmail(rs.getString("email"));
                mingrade = rs.getInt("总分");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            JDBCUtils.close(JDBCUtils.getRs(), JDBCUtils.getPs(),
                    JDBCUtils.getCt());
        }
        JOptionPane.showMessageDialog(null, "最低分的学生学号：" + stu.getStuid() + "，姓名："
                + stu.getName() + "，性别：" + stu.getSex() + "，总分：" + mingrade);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
    //}
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
